#! /bin/sh
# postinst script for mousetrap

set -e

case "$1" in
    configure)
      if ! getent passwd mousetrap 2>&1 >/dev/null; then
         # the account doesn't exist... time to create it
         echo "Adding mousetrap system user ..."
         adduser --quiet --system --group --home /dev/null mousetrap
         adduser --quiet mousetrap adm
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#
#DEBHELPER#
#

exit 0
