#! /bin/sh
# postrm script for mousetrapd

set -e

case "$1" in
       purge)
         if getent passwd mousetrapd 2>&1 >/dev/null; then
             echo -n "Removing mousetrapd system user.."
             userdel mousetrapd
             echo ".done"
         fi

         ;;
       remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
         ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
